### ISSUE TITLE
Included in Pod::To::Markdown

### ISSUE THREAD

**Issue by softmoth** [0racle/p6-Pod-To-Markdown-Fenced#2]
Hi, I'd like to avoid duplication of effort if possible. This feature is separately implemented in Pod::To::Markdown as of https://github.com/softmoth/perl6-pod-to-markdown/commit/bf3a2e9bf3c23d47b25c19f40790c4409e639ecb

I just noticed this project, and would like to add you as a collaborator to Pod::To::Markdown as an alternative to maintaining separate projects, if there are any features you're not happy with in that project. I'm basically maintaining it by incorporating others' patches anyways, and the community is doing almost all the work!

The feature uses `:lang<perl6>` instead of `:info<perl6>`.

It also preserves the extra newline at the end, whereas your implementation strips it, in code examples like
```perl6
=begin code :lang<perl6>

# Notice the trailing newline before the `=end code`
# That newline is removed by To::Markdown::Fenced, but
# preserved by To::Markdown

=end code
```

I hope neither of these is an issue for migration.

Kind regards, Tim

**Comment by 0racle** [comment]
The module had bit-rotted anyways. I have deprecated it; README has been updated, and tests will now fail advising of the deprecation.
